extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start:
    present: false
  indentation:
    spaces: 2
    indent-sequences: consistent
  truthy:
    check-keys: false
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1
